name: Issue Webhook
on:
  issues:
    types: [opened]
jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to external API
        run: |
          curl -X GET -H "Content-Type: application/json"  https://desa.apipartner.bci.cl/api/version




